# the whole purpose of yaml file is not hardcoding the sources and targets, but make them modular and change them whenever needed.
# We will also add epochs and training parameters whenever needed in params.yaml

artifacts_root: artifacts # where to save artifacts from downloaded dataset

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing' # use actual download link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5 # Using VGG16
  updated_base_model_path: artifacts/prepare_base_model/updated_model.h5 # Changing FC layers for finetuing

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5